// Capture actual WebView2 controls. Public synthetic fixtures only; no DOM mockups.
const {chromium} = require('playwright');
const fs = require('node:fs/promises');
const path = require('node:path');
const root=path.resolve(__dirname,'..'), out=path.join(root,'docs/screenshots');
let temp;
async function main(){
 await fs.mkdir(out,{recursive:true});
 const cfg=JSON.parse(await fs.readFile(path.join(root,'.tmp/docs-capture-session.json'),'utf8'));
 temp=cfg.data_dir;
 const browser=await chromium.connectOverCDP(`http://127.0.0.1:${cfg.debug_port}`);
 const page=browser.contexts().flatMap(c=>c.pages()).find(p=>p.url()===`http://127.0.0.1:${cfg.port}/`);
 page.setDefaultTimeout(20000);
 const errors=[], shots=[];page.on('pageerror',e=>errors.push(e.message));
 await page.waitForFunction(()=>document.body.dataset.ready==='true');
 const shot=async(name)=>{await page.screenshot({path:path.join(out,name+'.png'),timeout:15000});shots.push(name);};
 const click=async s=>page.locator(s).click();
 const send=async(text, state='idle')=>{await page.locator('#prompt').fill(text);await click('#sendButton');await page.waitForFunction(s=>document.body.dataset.runState===s,state,{timeout:60000});};
 await click('[data-tab="workspace"]');
 await page.waitForFunction(()=>document.querySelector('.mobius-stage canvas')?.dataset.animating==='true');
 await shot('01-welcome');
 await send('/read README.md');
 await page.waitForFunction(()=>document.querySelector('.message.assistant .markdown-content')?.textContent.includes('工作区概览'));
 await shot('02-chat-workspace');
 await click('[data-tab="workspace"]');
 await page.locator('#fileTree button').filter({hasText:'settings.json'}).first().click();
 await shot('03-file-preview');await click('#closeFile');
 await click('#contextStatus');await shot('04-context');await click('#closeContext');
 await send('/edit settings.json | "max_steps":8 | "max_steps":12','approval');
 await page.locator('.event.approval').last().scrollIntoViewIfNeeded();await shot('05-write-approval');await page.locator('.approval-actions button').filter({hasText:'批准'}).last().click();
 await page.waitForFunction(()=>document.body.dataset.runState==='idle');
 await click('[data-tab="knowledge"]');
 await click('#newCard');
 await page.locator('#cardTitle').fill('受控写入：先预览，再确认');
 await page.locator('#cardTags').fill('agent, security, design');
 await page.locator('#cardContent').fill('## 设计决定\n文件更新先展示 diff，再由用户确认。\n\n## 实现要点\n- 工作区路径边界检查\n- expected_text 校验，避免覆盖新内容\n- 原子落盘与修改记录\n\n## 边界\n应用层约束不等于操作系统沙箱。');
 await shot('06-knowledge-card');await page.locator('#cardForm button[type="submit"]').click();
 await page.waitForFunction(()=>!document.querySelector('#cardDialog').open);
 await send('/draft 上下文压缩保留完整历史 | 摘要仅用于下一轮上下文构造；原始会话仍存储在 SQLite，可通过 read_history 回查。 | 这是一条适合跨会话复用的工程约束');
 await page.locator('#draftList button').first().click();await shot('07-card-draft');await click('#closeDraft');
 await click('#auditKnowledge');await page.locator('#knowledgeAudit').evaluate(e=>e.open=true);
 await page.locator('#cardList').scrollIntoViewIfNeeded();await shot('08-knowledge-library');
 await click('#openPaperLibrary');await page.waitForSelector('#treeViewport canvas');
 await page.waitForTimeout(1500);await shot('09-paper-tree');
 const first=await page.locator('#treeViewport canvas').screenshot();
 const box=await page.locator('#treeViewport canvas').boundingBox();
 await page.mouse.move(box.x+box.width*.7,box.y+box.height*.45);await page.mouse.down();
 await page.mouse.move(box.x+box.width*.5,box.y+box.height*.55,{steps:12});await page.mouse.up();
 await page.waitForTimeout(500);const second=await page.locator('#treeViewport canvas').screenshot();
 if(first.equals(second))throw Error('Tree did not respond to orbit drag');
 await click('#listMode');await shot('10-paper-list');
 await page.locator('#paperTableBody button').first().click();await shot('11-paper-detail');
 await click('#readPaper');await page.waitForFunction(()=>{const img=document.querySelector('#paperPageImage');return img?.complete&&img.naturalWidth>0&&!img.hidden;});
 await shot('12-paper-reader');await click('#closePaperReader');await click('#closePaperLibrary');
 await click('#settingsButton');await shot('13-settings');
 if(!await page.locator('#guidanceEditor').evaluate(e=>e.open))await click('#guidanceEditor summary');
 await page.locator('#guidanceEditor').scrollIntoViewIfNeeded();await shot('14-routing-settings');await click('#closeSettings');
 await send('什么样的新证据会让你改变目前的判断？');await click('#routeDetails');await shot('15-route-details');await click('#closeRoute');
 await page.locator('#attachmentInput').setInputFiles([path.join(temp,'demo-workspace/notes.md'),path.join(root,'assets/web/brand/mobius.png')]);
 await page.waitForFunction(()=>document.querySelectorAll('#attachmentTray button').length>=2&&!document.querySelector('#attachmentTray').textContent.includes('上传中'));await shot('16-attachments');
 await page.waitForFunction(()=>!document.querySelector('#composerModel').disabled);await click('#composerModel');await page.waitForSelector('#composerModelChoices button');await shot('17-model-picker');
 await page.locator('#composerModelPopover').dispatchEvent('keydown',{key:'Escape',bubbles:true});
 const report={screenshots:shots,rendererErrors:errors,method:'native WebView2; synthetic fixture PDFs and offline response; not model-quality evidence',treeOrbitChangesPixels:!first.equals(second),pdfPageLoaded:true};
 await fs.writeFile(path.join(out,'capture-report.json'),JSON.stringify(report,null,2));
 console.log(JSON.stringify(report));
 if(errors.length)throw Error('Renderer errors');
}
main().then(async()=>{await fs.writeFile(path.join(temp,'finished'),'done');process.exit(0);}).catch(async e=>{console.error(e.stack);if(temp)await fs.writeFile(path.join(temp,'finished'),'failed');process.exit(1);});
